version: '3.8'
services:
  ollama:
    image: ollama/ollama:0.6.7-rc0
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./data/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - maowrag-open-llm
networks:
  maowrag-open-llm:
    driver: bridge