version: '3.8'
services:
  ollama:
    image: ollama/ollama:0.6.7-rc0
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./data/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - maowrag-open-llm
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - maowrag-open-llm

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - 8501:8501
    env_file:
      - .env
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_API_URL=http://backend:8000
    volumes:
      - .:/app
    networks:
      - maowrag-open-llm
networks:
  maowrag-open-llm:
    driver: bridge